
package stubclasses;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WineStockServiceImplementation", targetNamespace = "http://winery.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WineStockServiceImplementation {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://winery.fiap.com.br/", className = "stubclasses.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://winery.fiap.com.br/", className = "stubclasses.GetMenuResponse")
    @Action(input = "http://winery.fiap.com.br/WineStockServiceImplementation/getMenuRequest", output = "http://winery.fiap.com.br/WineStockServiceImplementation/getMenuResponse")
    public String getMenu();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://winery.fiap.com.br/", className = "stubclasses.PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://winery.fiap.com.br/", className = "stubclasses.PlaceOrderResponse")
    @Action(input = "http://winery.fiap.com.br/WineStockServiceImplementation/placeOrderRequest", output = "http://winery.fiap.com.br/WineStockServiceImplementation/placeOrderResponse")
    public String placeOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
